project:
  type: book

book:
  title: "SDC Handbook"
  subtitle: "ESSNet SDC"
  author: "Various Editors"
  date: "20/01/2023"
  chapters:
    - index.qmd
    - 02-regulations_with_tex.qmd
    - 03-microdata_with_tex.qmd
    - 04-magnitude-tabular-data_with_tex.qmd
    - 05-frequency-tables_with_tex.qmd
    - 06-remote-access-issues_with_tex.qmd
    - 07-glossary_with_tex.qmd
    - 08-final-index_with_tex.qmd
    - 09-references_with_tex.qmd
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    pdf-engine: latexmk
    pdf-engine-opt: -xelatex
    documentclass: scrreprt