project:
  type: book

book:
  title: "SDC Handbook"
  subtitle: "ESSNet SDC"
  author: "Various Editors"
  date: "20/01/2023"
  chapters:
    - index.qmd
    - 02-regulations.qmd
    - 03-microdata.qmd
    - 04-magnitude-tabular-data.qmd
    - 05-frequency-tables.qmd
    - 06-remote-access-issues.qmd
    - 07-glossary.qmd
    - 08-final-index.qmd
  page-navigation: true

bibliography: references.bib

format:
  html:
    theme: 
      - cosmo
      - custom.scss
#  pdf:
#    pdf-engine: xelatex
#    fig-pos: 'h'
#    documentclass: book
#    toc: true
#    keep-tex: true
#    include-in-header: 
#      text: |
#        \usepackage[english]{babel}
#        \usepackage[margin=3cm]{geometry}
#        \usepackage[utf8]{inputenc}
#        \usepackage{float}
#        \makeatletter
#        \renewenvironment{table}
#          {\@float{table}[H]}
#          {\end@float}
#        \makeatother
#        \counterwithout{footnote}{chapter}
#        \usepackage{makeidx}
#        \makeindex
#    include-after-body: 
#      text: |
#        \printindex

execute:
  freeze: auto
